#!/bin/zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

deactivate_copy () {
        if [ -n "${_OLD_VIRTUAL_PATH:-}" ]
        then
                PATH="${_OLD_VIRTUAL_PATH:-}" 
                export PATH
                unset _OLD_VIRTUAL_PATH
        fi
        if [ -n "${_OLD_VIRTUAL_PYTHONHOME:-}" ]
        then
                PYTHONHOME="${_OLD_VIRTUAL_PYTHONHOME:-}" 
                export PYTHONHOME
                unset _OLD_VIRTUAL_PYTHONHOME
        fi
        if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ]
        then
                hash -r 2> /dev/null
        fi
        if [ -n "${_OLD_VIRTUAL_PS1:-}" ]
        then
                PS1="${_OLD_VIRTUAL_PS1:-}" 
                export PS1
                unset _OLD_VIRTUAL_PS1
        fi
        unset VIRTUAL_ENV
        unset VIRTUAL_ENV_PROMPT
        if [ ! "${1:-}" = "nondestructive" ]
        then
                unset -f deactivate_copy
        fi
}

switch_env() {
	deactivate_copy &> /dev/null

	{
		source "$PWD/venv_$( basename $PWD )/bin/activate" &&
		printf "%b✓ switched to:%b venv_$( basename $PWD ) \n" $GREEN $NC
	} || {
		printf "%b✗ could not find venv%b \n" $RED $NC
		return 1
	}
}

create_env() {
	if [ -d "$PWD/venv_$( basename $PWD )" ]; then
		printf "%b✗ venv already exists%b \n" $RED $NC
		return 1
	
	else	
		deactivate_copy &> /dev/null

		python -m venv "venv_$( basename $PWD )" 
		printf "%b✓ created:%b venv_$( basename $PWD ) \n" $GREEN $NC
	fi
}

remove_env() {
	deactivate_copy &> /dev/null

	if [ -d "$PWD/venv_$( basename $PWD )" ]; then
		rm -rf "$PWD/venv_$( basename $PWD )"
	else
		printf "%b✗ could not find venv%b \n" $RED $NC
		return 1
	fi
}


usage() { printf "%s" "\
Usage: pyenv --options

Manage python virtual envs

Options:
	-c, --create		Create a python venv in the current git repository.

	-s, --switch		Switch venv: deactivate current venv and activate the
				one in the current git repository.

	-r, --remove		Remove the python venv in the current git repository.

	-d, --deactivate	Deactivate the active python venv.	

	-h, --help		Display the current help message.
"
return 1
}


PARSED_ARGS=$(getopt -o :csrdh --long create,switch,remove,deactivate,help -n 'penv' -- "$@")

if (( $? != 0 )) ; then echo "Found invalid options, try 'pyenv -h'." >&2 ; return 1 ; fi
if (( $# == 0 )) ; then usage; fi


eval set -- "$PARSED_ARGS"


while true; do
    case "$1" in
	-c | --create) create_env ;;
	-s | --switch) switch_env ;;
	-r | --remove) remove_env ;;
	-d | --deactivate) deactivate_copy ;;
	-h | --help) usage ;;
	--) shift; break ;;
	*)
	    echo "Invalid option $1"
	    usage
	    ;;
    esac

    shift
done


